<template>
  <div class="doc-list-page">
    <input ref="coverInput" class="sr-only" type="file" accept="image/*" @change="replaceCover" />
    <section v-if="docStore.viewMode === 'documents' && !docStore.currentFolderId" class="workspace-banner"><img src="/imgs/hero-banner.jpg" alt="团队在线协作" /><div><h1>文档工作区</h1><p>集中整理知识，与团队保持同步</p></div></section>
    <header class="page-header"><div><h2>{{ pageTitle }}</h2><span>{{ filteredDocs.length }} 篇文档</span></div><button v-if="docStore.viewMode !== 'trash'" class="btn btn-primary" type="button" @click="createOpen = true"><Plus :size="18" />新建文档</button></header>
    <p v-if="docStore.viewMode === 'trash'" class="trash-notice"><Trash2 :size="15" />回收站中的文档保留 {{ docStore.trashRetentionDays }} 天，到期后系统会自动彻底删除。</p>

    <div v-if="docStore.docs.length" class="list-tools">
      <label class="select-all"><input type="checkbox" :checked="allSelected" @change="toggleAll" />全选</label>
      <select v-model="categoryFilter" class="input category-filter"><option value="">全部分类</option><option v-for="category in categories" :key="category">{{ category }}</option></select>
      <div v-if="selectedIds.length" class="batch-actions"><span>已选 {{ selectedIds.length }} 项</span><button v-if="docStore.viewMode !== 'trash'" class="btn btn-secondary btn-sm" type="button" @click="openBatchMove"><FolderInput :size="14" />移动</button><button v-if="docStore.viewMode !== 'trash'" class="btn btn-secondary btn-sm" type="button" @click="runBatch('trash')"><Trash2 :size="14" />删除</button><button v-else class="btn btn-secondary btn-sm" type="button" @click="runBatch('restore')"><RotateCcw :size="14" />恢复</button><button v-if="docStore.viewMode === 'trash'" class="btn btn-secondary btn-sm danger-text" type="button" @click="runBatch('purge')"><Trash2 :size="14" />彻底删除</button></div>
    </div>

    <div v-if="docStore.loading" class="state"><Loader2 :size="30" class="spin" /><p>正在加载文档</p></div>
    <div v-else-if="filteredDocs.length||showGuide" class="doc-grid">
      <article v-if="showGuide" class="doc-card guide-card" @click="guideOpen=true"><div class="guide-cover"><BookOpen :size="28"/></div><div class="doc-card-body"><div class="doc-card-header"><div class="doc-title"><BookOpen :size="18"/><span>云笺协作指南</span></div><button class="btn btn-icon btn-ghost" type="button" title="不再显示" @click.stop="dismissGuide"><X :size="15"/></button></div><div class="doc-meta"><span>内置指南</span><small>只读</small></div><p class="doc-summary">邀请伙伴共同编辑，使用批注、修订和版本历史完成团队审阅。</p><footer><span>重要功能</span><span>协作入门</span></footer></div></article>
      <article v-for="doc in filteredDocs" :key="doc.id" :class="['doc-card', { selected: selectedIds.includes(doc.id) }]" @click="openDoc(doc)">
        <label class="card-select" @click.stop><input type="checkbox" :checked="selectedIds.includes(doc.id)" @change="toggleDoc(doc.id)" /><span class="sr-only">选择文档</span></label>
        <img class="doc-cover" :src="doc.coverImage||'/imgs/default-cover.jpg'" alt="" />
        <div class="doc-card-body"><div class="doc-card-header"><div class="doc-title"><FileText :size="18" /><span>{{ doc.title || '无标题文档' }}</span></div></div><div :class="['doc-card-tools', { 'trash-card-tools': docStore.viewMode === 'trash' }]"><div class="doc-meta"><span v-if="doc.category">{{ doc.category }}</span></div><div :class="['doc-actions', { 'trash-actions': docStore.viewMode === 'trash' }]" @click.stop>
          <button v-if="docStore.viewMode !== 'trash'" class="btn btn-icon btn-ghost" type="button" title="修改封面" @click="chooseCover(doc)"><ImagePlus :size="15" /></button>
          <button v-if="docStore.viewMode !== 'trash'" class="btn btn-icon btn-ghost" type="button" :title="doc.isFavorite ? '取消收藏' : '收藏'" @click="handleFavorite(doc)"><Star :size="15" :class="{ favorite: doc.isFavorite }" /></button>
          <button v-if="docStore.viewMode !== 'trash'" class="btn btn-icon btn-ghost" type="button" :title="doc.isPinned ? '取消置顶' : '置顶'" @click="handlePin(doc)"><Pin :size="15" :class="{ pinned: doc.isPinned }" /></button>
          <button v-if="docStore.viewMode !== 'trash'" class="btn btn-icon btn-ghost" type="button" title="移动" @click="openMove(doc)"><FolderInput :size="15" /></button>
          <button v-if="docStore.viewMode !== 'trash'" class="btn btn-icon btn-ghost" type="button" title="复制" @click="handleCopy(doc)"><Copy :size="15" /></button>
          <button v-if="docStore.viewMode !== 'trash'" class="btn btn-icon btn-ghost danger" type="button" title="移到回收站" @click="handleDelete(doc)"><Trash2 :size="15" /></button>
          <button v-else class="btn btn-ghost btn-sm" type="button" @click="handleRestore(doc)"><RotateCcw :size="14" />恢复</button><button v-if="docStore.viewMode === 'trash'" class="btn btn-ghost btn-sm danger-text" type="button" @click="handlePurge(doc)">彻底删除</button>
        </div></div><p class="doc-summary">{{ doc.summary || '这篇文档还没有内容' }}</p><footer><span><Clock :size="13" />{{ formatTime(doc.updatedAt) }}</span><span>{{ docStore.viewMode === 'trash' ? trashRemaining(doc) : (doc.collabMode === 'CRDT' ? '实时协作' : '自动保存') }}</span></footer></div>
      </article>
    </div>
    <div v-else class="state empty-state"><img src="../assets/empty-docs.svg" alt="暂无文档" /><h3>{{ docStore.viewMode === 'trash' ? '回收站是空的' : '还没有文档' }}</h3><p>{{ docStore.viewMode === 'trash' ? '删除的文档会暂时保留在这里' : '创建第一篇文档开始记录' }}</p><button v-if="docStore.viewMode !== 'trash'" class="btn btn-primary" type="button" @click="createOpen = true"><Plus :size="18" />创建文档</button></div>

    <div v-if="moveDialog.open" class="modal-backdrop" @click.self="moveDialog.open = false"><form class="modal" @submit.prevent="submitMove"><header><h2>移动文档</h2><button class="btn btn-icon btn-ghost" type="button" @click="moveDialog.open = false"><X :size="18" /></button></header><label>目标文件夹<select v-model.number="moveDialog.folderId" class="input"><option :value="0">根目录</option><option v-for="folder in docStore.folders" :key="folder.id" :value="folder.id">{{ folder.name }}</option></select></label><footer><button class="btn btn-secondary" type="button" @click="moveDialog.open = false">取消</button><button class="btn btn-primary" type="submit">移动</button></footer></form></div>
    <div v-if="guideOpen" class="modal-backdrop" @click.self="guideOpen=false"><article class="modal guide-modal"><header><div><h2>云笺协作指南</h2><p>一篇不会被误改的内置说明</p></div><button class="btn btn-icon btn-ghost" type="button" @click="guideOpen=false"><X :size="18"/></button></header><section><h3>从邀请协作者开始</h3><p>在文档右上角打开“协作者”，按用户名邀请伙伴，并设置只读、仅批注、编辑或管理权限。</p><h3>一起编辑与审阅</h3><p>CRDT 会合并同时发生的修改。需要正式审阅时，可打开修订模式，结合批注线程、版本命名和版本对比确认内容。</p><h3>保存与交付</h3><p>重要节点可以保存手动版本，最终可导出 DOCX、服务端 PDF 或完全离线的 HTML 文件。</p></section><footer><button class="btn btn-secondary" type="button" @click="dismissGuide">不再显示</button><button class="btn btn-primary" type="button" @click="guideOpen=false;createOpen=true">新建协作文档</button></footer></article></div>
    <CreateDocumentDialog :open="createOpen" :folder-id="docStore.currentFolderId" @close="createOpen = false" @created="doc => router.push(`/doc/${doc.id}`)" />
  </div>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { BookOpen, Clock, Copy, FileText, FolderInput, ImagePlus, Loader2, Pin, Plus, RotateCcw, Star, Trash2, X } from 'lucide-vue-next'
import dayjs from 'dayjs'; import relativeTime from 'dayjs/plugin/relativeTime'; import 'dayjs/locale/zh-cn'
import CreateDocumentDialog from '../components/CreateDocumentDialog.vue'
import { useDocStore, useUserStore } from '../store'; import { docApi, fileApi, userApi } from '../api'; import { error, success } from '../utils/toast'
import { confirmDialog } from '../utils/dialog'

dayjs.extend(relativeTime); dayjs.locale('zh-cn')
const router = useRouter(); const docStore = useDocStore(); const userStore=useUserStore(); const createOpen = ref(false);const guideOpen=ref(false); const selectedIds = ref([]); const categoryFilter = ref(''); const moveDialog = reactive({ open: false, doc: null, folderId: 0, batch: false });const coverInput=ref(null),coverTarget=ref(null)
const categories = computed(() => [...new Set(docStore.docs.map(doc => doc.category).filter(Boolean))].sort())
const filteredDocs = computed(() => categoryFilter.value ? docStore.docs.filter(doc => doc.category === categoryFilter.value) : docStore.docs)
const allSelected = computed(() => filteredDocs.value.length > 0 && filteredDocs.value.every(doc => selectedIds.value.includes(doc.id)))
const pageTitle = computed(() => ({ trash: '回收站', search: '搜索结果', recent: '最近编辑', favorites: '我的收藏' }[docStore.viewMode] || docStore.folders.find(folder => folder.id === docStore.currentFolderId)?.name || '全部文档'))
const showGuide=computed(()=>docStore.viewMode==='documents'&&!docStore.currentFolderId&&!Number(userStore.user?.welcomeDismissed||0))
watch(() => docStore.viewMode, () => { selectedIds.value = []; categoryFilter.value = '' })
const formatTime = time => time ? dayjs(time).fromNow() : '刚刚'; const openDoc = doc => { if (!doc.isDeleted) router.push(`/doc/${doc.id}`) }
function trashRemaining(doc) { const deletedAt = dayjs(doc.deletedAt || doc.updatedAt); const days = Math.max(0, docStore.trashRetentionDays - dayjs().diff(deletedAt, 'day')); return days > 0 ? `剩余约 ${days} 天` : '即将自动删除' }
function toggleDoc(id) { selectedIds.value = selectedIds.value.includes(id) ? selectedIds.value.filter(item => item !== id) : [...selectedIds.value, id] }
function toggleAll() { const ids = filteredDocs.value.map(doc => doc.id); selectedIds.value = allSelected.value ? selectedIds.value.filter(id => !ids.includes(id)) : [...new Set([...selectedIds.value, ...ids])] }
async function run(action, text, fallback) { try { await action(); success(text) } catch (exception) { error(exception.message || fallback) } }
function handlePin(doc) { run(() => docStore.togglePin(doc), doc.isPinned ? '已取消置顶' : '已置顶', '置顶失败') }
function handleFavorite(doc) { run(() => docStore.toggleFavorite(doc), doc.isFavorite ? '已取消收藏' : '已收藏', '收藏失败') }
function handleCopy(doc) { run(() => docStore.copyDoc(doc), '文档已复制', '复制失败') }
async function handleDelete(doc) { if (await confirmDialog(`将“${doc.title}”移到回收站？`, { title: '删除文档', confirmText: '移到回收站', danger: true })) run(() => docStore.deleteDoc(doc.id), '已移到回收站', '删除失败') }
function handleRestore(doc) { run(() => docStore.restoreDoc(doc.id), '文档已恢复', '恢复失败') }
async function handlePurge(doc) { if (await confirmDialog(`彻底删除“${doc.title}”？删除后无法恢复。`, { title: '彻底删除文档', confirmText: '彻底删除', danger: true })) run(() => docStore.purgeDoc(doc.id), '文档已彻底删除', '彻底删除失败') }
function chooseCover(doc){coverTarget.value=doc;coverInput.value?.click()}
async function replaceCover(event){const file=event.target.files?.[0];event.target.value='';if(!file||!coverTarget.value)return;if(!file.type.startsWith('image/'))return error('请选择图片文件');if(file.size>10*1024*1024)return error('封面图片不能超过 10 MB');try{const uploaded=await fileApi.uploadImage(file);const updated=await docApi.update(coverTarget.value.id,{coverImage:uploaded.data.url});Object.assign(coverTarget.value,updated.data);success('封面已更新')}catch(exception){error(exception.message||'封面更新失败')}finally{coverTarget.value=null}}
function openMove(doc) { Object.assign(moveDialog, { open: true, doc, folderId: doc.folderId || 0, batch: false }) }
function openBatchMove() { Object.assign(moveDialog, { open: true, doc: null, folderId: 0, batch: true }) }
async function submitMove() { if (moveDialog.batch) await runBatch('move', moveDialog.folderId); else await run(() => docStore.moveDoc(moveDialog.doc, moveDialog.folderId), '文档已移动', '移动失败'); moveDialog.open = false }
async function runBatch(action, folderId) { if (!selectedIds.value.length) return; if (action === 'trash' || action === 'purge') { const purge = action === 'purge'; const confirmed = await confirmDialog(purge ? `彻底删除选中的 ${selectedIds.value.length} 篇文档？删除后无法恢复。` : `将选中的 ${selectedIds.value.length} 篇文档移到回收站？`, { title: purge ? '彻底删除文档' : '删除文档', confirmText: purge ? '彻底删除' : '移到回收站', danger: true }); if (!confirmed) return } try { await docStore.batch(action, selectedIds.value, folderId); success('批量操作完成'); selectedIds.value = [] } catch (exception) { error(exception.message || '批量操作失败') } }
async function dismissGuide(){try{const response=await userApi.dismissWelcome();userStore.updateUser(response.data);guideOpen.value=false;success('协作指南已隐藏')}catch(exception){error(exception.message||'操作失败')}}
</script>

<style scoped>
.doc-list-page { width: min(1240px,100%); min-height: 100%; margin: 0 auto; padding: 22px 28px 40px; }.workspace-banner { position: relative; height: 150px; overflow: hidden; margin-bottom: 22px; border-radius: 8px; background: #08245f; color: white; }.workspace-banner img { width:100%;height:100%;object-fit:cover; }.workspace-banner div { position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;padding-left:34px;background:linear-gradient(90deg,rgba(4,20,59,.8),transparent 58%); }.workspace-banner h1{font-size:25px}.workspace-banner p{margin-top:4px;color:#c9dcff}
.page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.page-header>div{display:flex;align-items:baseline;gap:10px}.page-header h2{font-size:20px}.page-header span{color:var(--text-muted);font-size:13px}.list-tools{min-height:44px;display:flex;align-items:center;gap:12px;margin-bottom:14px;padding:7px 10px;border:1px solid var(--border);border-radius:7px;background:white}.select-all{display:flex;align-items:center;gap:6px;font-size:13px}.category-filter{width:150px;height:32px;padding:5px 8px}.batch-actions{display:flex;align-items:center;gap:7px;margin-left:auto}.batch-actions>span{color:var(--text-secondary);font-size:12px}
.trash-notice{display:flex;align-items:center;gap:7px;margin:-4px 0 14px;padding:9px 11px;border:1px solid #fde68a;border-radius:6px;background:#fffbeb;color:#854d0e;font-size:12px}
.doc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:16px}.doc-card{position:relative;min-width:0;overflow:hidden;border:1px solid var(--border);border-radius:7px;background:white;cursor:pointer;transition:.15s}.doc-card:hover,.doc-card.selected{transform:translateY(-2px);border-color:#80aaf0;box-shadow:var(--shadow-lg)}.card-select{position:absolute;top:8px;left:8px;z-index:2;width:24px;height:24px;display:grid;place-items:center;border-radius:4px;background:rgba(255,255,255,.92)}.doc-cover{display:block;width:100%;height:94px;object-fit:cover;border-bottom:1px solid var(--border-light)}.doc-card-body{padding:14px}.doc-card-header{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.doc-title{min-width:0;display:flex;align-items:center;gap:7px;font-weight:650}.doc-title svg{flex:0 0 auto;color:var(--primary)}.doc-title span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.doc-card-tools{min-height:30px;display:flex;align-items:center;justify-content:space-between;gap:4px;margin-top:6px}.doc-actions{display:flex;opacity:1}.doc-actions .btn{width:25px;height:25px;padding:0}.trash-card-tools{justify-content:flex-end}.trash-card-tools .doc-meta:empty{display:none}.doc-actions.trash-actions{gap:7px;margin-left:auto}.doc-actions.trash-actions .btn{width:auto;min-width:70px;height:30px;padding:5px 9px;justify-content:center}.doc-actions.trash-actions .danger-text{border:1px solid #fecaca;background:#fff7f7}.favorite{color:#eab308;fill:#fef08a}.pinned{color:var(--warning);fill:#fef3c7}.danger-text{color:var(--danger)}.doc-meta{min-width:0;display:flex;gap:6px}.doc-meta span,.doc-meta small{padding:2px 6px;border-radius:4px;background:#eef4ff;color:#315f9f;font-size:10px}.doc-meta small{background:#f1f5f9;color:#64748b}.doc-summary{height:42px;margin:8px 0 12px;overflow:hidden;color:var(--text-secondary);font-size:13px;line-height:21px}.doc-card footer{display:flex;justify-content:space-between;color:var(--text-muted);font-size:12px}.doc-card footer span{display:flex;align-items:center;gap:4px}
.guide-cover{height:94px;display:grid;place-items:center;background:#eaf2ff;color:#2563eb;border-bottom:1px solid #bfdbfe}.guide-card{border-color:#bfdbfe}.guide-modal{width:min(620px,calc(100vw - 28px))}.guide-modal>header p{margin-top:3px;color:var(--text-muted);font-size:12px}.guide-modal>section{display:grid;gap:6px;max-height:60vh;overflow:auto}.guide-modal h3{margin-top:8px;font-size:15px}.guide-modal section p{color:var(--text-secondary);line-height:1.7}.guide-modal>footer{display:flex;justify-content:flex-end;gap:8px}
.state{min-height:360px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;color:var(--text-muted)}.empty-state img{width:190px;height:190px}.empty-state h3{color:var(--text);font-size:17px}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
@media(max-width:768px){.doc-list-page{padding:16px 14px 76px}.workspace-banner{height:116px}.workspace-banner div{padding-left:18px}.workspace-banner h1{font-size:20px}.doc-grid{grid-template-columns:1fr}.doc-actions{opacity:1}.list-tools{align-items:flex-start;flex-wrap:wrap}.batch-actions{width:100%;margin-left:0;overflow-x:auto}.category-filter{margin-left:auto}}
</style>
